version: "3.3"
services:
  my-mongo-db:
    container_name: my-mongo-db
    image: mongo:4.4.3
    ports:
      - "8801:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  backend: 
    build: ./API
    ports: 
      - "8800:8800"
